# Generated by Django 4.0.6 on 2022-08-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rayan_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
