# Generated by Django 4.0.6 on 2022-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customerbrokerbourseaccounts_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbankaccount',
            name='shaba',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
