# Generated by Django 4.0.6 on 2022-08-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customerbankaccount_shaba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerportfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customerportfo',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerportfo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customerportfo',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='customerfund',
            unique_together={('customer_service', 'fund_name')},
        ),
    ]
