# Generated by Django 4.0.6 on 2022-08-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customerportfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfund',
            name='fullname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
