# Generated by Django 4.0.6 on 2022-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20220920_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfinancialinfo',
            name='c_exchange_tranasction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerfinancialinfo',
            name='out_exchange_tranasction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerfinancialinfo',
            name='s_exchange_tranasction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerfinancialinfo',
            name='trading_knowledge_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerfinancialinfo',
            name='tranasction_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
