# Generated by Django 4.0.6 on 2022-11-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_basefund'),
        ('customer', '0011_alter_customerfinancialinfo_c_exchange_tranasction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfund',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.basefund'),
        ),
    ]
