# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsms.proto\"8\n\nSmsRequest\x12\x19\n\x0cname_service\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_name_service\"Y\n\x0eSmsSendRequest\x12\x19\n\x0cname_service\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05phone\x18\x02 \x03(\t\x12\x0c\n\x04text\x18\x03 \x03(\tB\x0f\n\r_name_service\"M\n\x10SmsStatusRequest\x12\x19\n\x0cname_service\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05phone\x18\x02 \x03(\tB\x0f\n\r_name_service\" \n\x0eSmsMagfaStatus\x12\x0e\n\x06status\x18\x01 \x03(\t\"@\n\x1dSmsMagfaStatusServiceResponse\x12\x1f\n\x06result\x18\x01 \x01(\x0b\x32\x0f.SmsMagfaStatus\"\x1a\n\x08SmsMagfa\x12\x0e\n\x06sms_id\x18\x01 \x03(\t\"I\n\x17SmsMagfaServiceResponse\x12\x19\n\x06result\x18\x01 \x01(\x0b\x32\t.SmsMagfa\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"5\n\x05SmsDb\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\t\".\n\x14SmsDbServiceResponse\x12\x16\n\x06result\x18\x01 \x03(\x0b\x32\x06.SmsDb2\xc0\x01\n\nSmsService\x12\x37\n\nSmsService\x12\x0f.SmsSendRequest\x1a\x18.SmsMagfaServiceResponse\x12\x32\n\x0cSmsDbService\x12\x0b.SmsRequest\x1a\x15.SmsDbServiceResponse\x12\x45\n\x10SmsStatusService\x12\x11.SmsStatusRequest\x1a\x1e.SmsMagfaStatusServiceResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SMSREQUEST._serialized_start=13
  _SMSREQUEST._serialized_end=69
  _SMSSENDREQUEST._serialized_start=71
  _SMSSENDREQUEST._serialized_end=160
  _SMSSTATUSREQUEST._serialized_start=162
  _SMSSTATUSREQUEST._serialized_end=239
  _SMSMAGFASTATUS._serialized_start=241
  _SMSMAGFASTATUS._serialized_end=273
  _SMSMAGFASTATUSSERVICERESPONSE._serialized_start=275
  _SMSMAGFASTATUSSERVICERESPONSE._serialized_end=339
  _SMSMAGFA._serialized_start=341
  _SMSMAGFA._serialized_end=367
  _SMSMAGFASERVICERESPONSE._serialized_start=369
  _SMSMAGFASERVICERESPONSE._serialized_end=442
  _SMSDB._serialized_start=444
  _SMSDB._serialized_end=497
  _SMSDBSERVICERESPONSE._serialized_start=499
  _SMSDBSERVICERESPONSE._serialized_end=545
  _SMSSERVICE._serialized_start=548
  _SMSSERVICE._serialized_end=740
# @@protoc_insertion_point(module_scope)
