# Generated by Django 4.0.6 on 2022-09-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('base', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_bank',
            },
        ),
        migrations.CreateModel(
            name='BaseCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_countries',
            },
        ),
        migrations.CreateModel(
            name='BaseFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('fa_name', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_force', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_file_type',
            },
        ),
        migrations.CreateModel(
            name='BaseGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'base_gender',
            },
        ),
        migrations.CreateModel(
            name='BaseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('title', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('job_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'base_job',
            },
        ),
        migrations.CreateModel(
            name='BaseMebbcoBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type_mebbco', models.CharField(blank=True, max_length=50, null=True)),
                ('id_rayan', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'base_mebbco_branch',
            },
        ),
        migrations.CreateModel(
            name='BaseMebbcoDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('title', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('id_rayan', models.IntegerField(blank=True, null=True)),
                ('rayan_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_mebbco_domain',
            },
        ),
        migrations.CreateModel(
            name='BaseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('state_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_state',
            },
        ),
        migrations.CreateModel(
            name='BaseProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('province_id', models.IntegerField(blank=True, null=True)),
                ('rayan_province_id', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.basecountries')),
            ],
            options={
                'db_table': 'base_province',
            },
        ),
        migrations.CreateModel(
            name='BaseCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('rayan_city_id', models.IntegerField(blank=True, null=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.baseprovince')),
            ],
            options={
                'db_table': 'base_cities',
            },
        ),
        migrations.CreateModel(
            name='BaseBankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rayan_bank_id', models.TextField(blank=True, null=True)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('bank_branch_id', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('sejam_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dl_number', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.basecities')),
            ],
            options={
                'db_table': 'base_bank_branch',
            },
        ),
    ]
