# Generated by Django 4.0.6 on 2022-08-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_basebank_bank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecities',
            name='rayan_city_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='baseprovince',
            name='rayan_province_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
