# Generated by Django 4.0.6 on 2022-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_basecities_rayan_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprovince',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
