# Generated by Django 4.0.6 on 2022-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_basecities_name_alter_basecountries_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecities',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
