# Generated by Django 4.0.6 on 2022-08-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_basecities_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basebankbranch',
            old_name='rayan_bank_id',
            new_name='rayan_branch_id',
        ),
        migrations.AlterUniqueTogether(
            name='basecities',
            unique_together={('name', 'province')},
        ),
    ]
