# Generated by Django 4.0.6 on 2022-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_rayan_bank_id_basebankbranch_rayan_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebankbranch',
            name='rayan_branch_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
