# Generated by Django 4.0.6 on 2022-09-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_basebankbranch_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecities',
            name='sejam_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
