# Generated by Django 4.0.6 on 2022-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_basecities_sejam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebank',
            name='sejam_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
