# Generated by Django 4.0.6 on 2022-09-28 08:04

from django.db import migrations

def create_data(apps, schema_editor):
    BaseState = apps.get_model('base', 'BaseState')
    states = [
        {"state_name": "person_info", "title": "اطلاعات هویتی", "icon_class": "fas fa-briefcase", "state_id": 1},
        {"state_name": "contact_us", "title": "اطلاعات تماس", "icon_class": "fas fa-book-reader", "state_id": 2},
        {"state_name": "account_info", "title": "اطلاعات حساب", "icon_class": "fas fa-people-arrows", "state_id": 3},
        {"state_name": "job_experience", "title": "اطلاعات کاری", "icon_class": "fas fa-users", "state_id": 4},
        {"state_name": "asset", "title": "اطلاعات دارایی", "icon_class": "far fa-comment-alt", "state_id": 5},
        {"state_name": "contract", "title": "بارگزاری", "icon_class": "fas fa-images", "state_id": 6},
    ]

    for item in states:
        BaseState.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_basebank_sejam_id'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
