# Generated by Django 4.0.6 on 2022-11-08 07:03

from django.db import migrations


def create_data(apps, schema_editor):
    BaseFund = apps.get_model('base', 'BaseFund')
    states = [
        {"name": "fund1", "fa_name": "صندوق افق", "is_active": True},
        {"name": "fund2", "fa_name": "صندوق افق روشن", "is_active": True},
    ]

    for item in states:
        BaseFund.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_basefund'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
