# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\x12\x04\x62\x61nk\x1a\x1bgoogle/protobuf/empty.proto\"h\n\x08\x42\x61seBank\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63reated_date\x18\x02 \x01(\t\x12\x14\n\x0cupdated_date\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x15\n\rrayan_bank_id\x18\x05 \x01(\x03\"\x15\n\x13\x42\x61seBankListRequest\"%\n\x17\x42\x61seBankRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x95\x02\n\x12\x42\x61seBankController\x12\x35\n\x04List\x12\x19.bank.BaseBankListRequest\x1a\x0e.bank.BaseBank\"\x00\x30\x01\x12*\n\x06\x43reate\x12\x0e.bank.BaseBank\x1a\x0e.bank.BaseBank\"\x00\x12;\n\x08Retrieve\x12\x1d.bank.BaseBankRetrieveRequest\x1a\x0e.bank.BaseBank\"\x00\x12*\n\x06Update\x12\x0e.bank.BaseBank\x1a\x0e.bank.BaseBank\"\x00\x12\x33\n\x07\x44\x65stroy\x12\x0e.bank.BaseBank\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_BASEBANK = DESCRIPTOR.message_types_by_name['BaseBank']
_BASEBANKLISTREQUEST = DESCRIPTOR.message_types_by_name['BaseBankListRequest']
_BASEBANKRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['BaseBankRetrieveRequest']
BaseBank = _reflection.GeneratedProtocolMessageType('BaseBank', (_message.Message,), {
  'DESCRIPTOR' : _BASEBANK,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.BaseBank)
  })
_sym_db.RegisterMessage(BaseBank)

BaseBankListRequest = _reflection.GeneratedProtocolMessageType('BaseBankListRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASEBANKLISTREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.BaseBankListRequest)
  })
_sym_db.RegisterMessage(BaseBankListRequest)

BaseBankRetrieveRequest = _reflection.GeneratedProtocolMessageType('BaseBankRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASEBANKRETRIEVEREQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.BaseBankRetrieveRequest)
  })
_sym_db.RegisterMessage(BaseBankRetrieveRequest)

_BASEBANKCONTROLLER = DESCRIPTOR.services_by_name['BaseBankController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASEBANK._serialized_start=49
  _BASEBANK._serialized_end=153
  _BASEBANKLISTREQUEST._serialized_start=155
  _BASEBANKLISTREQUEST._serialized_end=176
  _BASEBANKRETRIEVEREQUEST._serialized_start=178
  _BASEBANKRETRIEVEREQUEST._serialized_end=215
  _BASEBANKCONTROLLER._serialized_start=218
  _BASEBANKCONTROLLER._serialized_end=495
# @@protoc_insertion_point(module_scope)
