# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: city.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncity.proto\x12\x04\x63ity\x1a\x1bgoogle/protobuf/empty.proto\"O\n\nBaseCities\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x15\n\rrayan_city_id\x18\x05 \x01(\t\x12\x10\n\x08province\x18\x06 \x01(\t\"\x17\n\x15\x42\x61seCitiesListRequest\"\'\n\x19\x42\x61seCitiesRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xa9\x02\n\x14\x42\x61seCitiesController\x12\x39\n\x04List\x12\x1b.city.BaseCitiesListRequest\x1a\x10.city.BaseCities\"\x00\x30\x01\x12.\n\x06\x43reate\x12\x10.city.BaseCities\x1a\x10.city.BaseCities\"\x00\x12?\n\x08Retrieve\x12\x1f.city.BaseCitiesRetrieveRequest\x1a\x10.city.BaseCities\"\x00\x12.\n\x06Update\x12\x10.city.BaseCities\x1a\x10.city.BaseCities\"\x00\x12\x35\n\x07\x44\x65stroy\x12\x10.city.BaseCities\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_BASECITIES = DESCRIPTOR.message_types_by_name['BaseCities']
_BASECITIESLISTREQUEST = DESCRIPTOR.message_types_by_name['BaseCitiesListRequest']
_BASECITIESRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['BaseCitiesRetrieveRequest']
BaseCities = _reflection.GeneratedProtocolMessageType('BaseCities', (_message.Message,), {
  'DESCRIPTOR' : _BASECITIES,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:city.BaseCities)
  })
_sym_db.RegisterMessage(BaseCities)

BaseCitiesListRequest = _reflection.GeneratedProtocolMessageType('BaseCitiesListRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASECITIESLISTREQUEST,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:city.BaseCitiesListRequest)
  })
_sym_db.RegisterMessage(BaseCitiesListRequest)

BaseCitiesRetrieveRequest = _reflection.GeneratedProtocolMessageType('BaseCitiesRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASECITIESRETRIEVEREQUEST,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:city.BaseCitiesRetrieveRequest)
  })
_sym_db.RegisterMessage(BaseCitiesRetrieveRequest)

_BASECITIESCONTROLLER = DESCRIPTOR.services_by_name['BaseCitiesController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASECITIES._serialized_start=49
  _BASECITIES._serialized_end=128
  _BASECITIESLISTREQUEST._serialized_start=130
  _BASECITIESLISTREQUEST._serialized_end=153
  _BASECITIESRETRIEVEREQUEST._serialized_start=155
  _BASECITIESRETRIEVEREQUEST._serialized_end=194
  _BASECITIESCONTROLLER._serialized_start=197
  _BASECITIESCONTROLLER._serialized_end=494
# @@protoc_insertion_point(module_scope)
