# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer_comex_visitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ustomer_comex_visitor.proto\x12\x16\x63ustomer_comex_visitor\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x01\n\x14\x43ustomerComexVisitor\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63reated_date\x18\x02 \x01(\t\x12\x14\n\x0cupdated_date\x18\x03 \x01(\t\x12\x16\n\x0e\x63omex_id_rayan\x18\x04 \x01(\x05\x12\x11\n\tfull_name\x18\x05 \x01(\t\x12\x0c\n\x04rate\x18\x06 \x01(\x05\x12\x13\n\x0btype_mebbco\x18\x07 \x01(\x03\"!\n\x1f\x43ustomerComexVisitorListRequest\"1\n#CustomerComexVisitorRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xaf\x04\n\x1e\x43ustomerComexVisitorController\x12q\n\x04List\x12\x37.customer_comex_visitor.CustomerComexVisitorListRequest\x1a,.customer_comex_visitor.CustomerComexVisitor\"\x00\x30\x01\x12\x66\n\x06\x43reate\x12,.customer_comex_visitor.CustomerComexVisitor\x1a,.customer_comex_visitor.CustomerComexVisitor\"\x00\x12w\n\x08Retrieve\x12;.customer_comex_visitor.CustomerComexVisitorRetrieveRequest\x1a,.customer_comex_visitor.CustomerComexVisitor\"\x00\x12\x66\n\x06Update\x12,.customer_comex_visitor.CustomerComexVisitor\x1a,.customer_comex_visitor.CustomerComexVisitor\"\x00\x12Q\n\x07\x44\x65stroy\x12,.customer_comex_visitor.CustomerComexVisitor\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_CUSTOMERCOMEXVISITOR = DESCRIPTOR.message_types_by_name['CustomerComexVisitor']
_CUSTOMERCOMEXVISITORLISTREQUEST = DESCRIPTOR.message_types_by_name['CustomerComexVisitorListRequest']
_CUSTOMERCOMEXVISITORRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['CustomerComexVisitorRetrieveRequest']
CustomerComexVisitor = _reflection.GeneratedProtocolMessageType('CustomerComexVisitor', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERCOMEXVISITOR,
  '__module__' : 'customer_comex_visitor_pb2'
  # @@protoc_insertion_point(class_scope:customer_comex_visitor.CustomerComexVisitor)
  })
_sym_db.RegisterMessage(CustomerComexVisitor)

CustomerComexVisitorListRequest = _reflection.GeneratedProtocolMessageType('CustomerComexVisitorListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERCOMEXVISITORLISTREQUEST,
  '__module__' : 'customer_comex_visitor_pb2'
  # @@protoc_insertion_point(class_scope:customer_comex_visitor.CustomerComexVisitorListRequest)
  })
_sym_db.RegisterMessage(CustomerComexVisitorListRequest)

CustomerComexVisitorRetrieveRequest = _reflection.GeneratedProtocolMessageType('CustomerComexVisitorRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERCOMEXVISITORRETRIEVEREQUEST,
  '__module__' : 'customer_comex_visitor_pb2'
  # @@protoc_insertion_point(class_scope:customer_comex_visitor.CustomerComexVisitorRetrieveRequest)
  })
_sym_db.RegisterMessage(CustomerComexVisitorRetrieveRequest)

_CUSTOMERCOMEXVISITORCONTROLLER = DESCRIPTOR.services_by_name['CustomerComexVisitorController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMERCOMEXVISITOR._serialized_start=86
  _CUSTOMERCOMEXVISITOR._serialized_end=242
  _CUSTOMERCOMEXVISITORLISTREQUEST._serialized_start=244
  _CUSTOMERCOMEXVISITORLISTREQUEST._serialized_end=277
  _CUSTOMERCOMEXVISITORRETRIEVEREQUEST._serialized_start=279
  _CUSTOMERCOMEXVISITORRETRIEVEREQUEST._serialized_end=328
  _CUSTOMERCOMEXVISITORCONTROLLER._serialized_start=331
  _CUSTOMERCOMEXVISITORCONTROLLER._serialized_end=890
# @@protoc_insertion_point(module_scope)
