# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from service.server.grpc import customer_comex_visitor_pb2 as customer__comex__visitor__pb2


class CustomerComexVisitorControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/customer_comex_visitor.CustomerComexVisitorController/List',
                request_serializer=customer__comex__visitor__pb2.CustomerComexVisitorListRequest.SerializeToString,
                response_deserializer=customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
                )
        self.Create = channel.unary_unary(
                '/customer_comex_visitor.CustomerComexVisitorController/Create',
                request_serializer=customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
                response_deserializer=customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/customer_comex_visitor.CustomerComexVisitorController/Retrieve',
                request_serializer=customer__comex__visitor__pb2.CustomerComexVisitorRetrieveRequest.SerializeToString,
                response_deserializer=customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
                )
        self.Update = channel.unary_unary(
                '/customer_comex_visitor.CustomerComexVisitorController/Update',
                request_serializer=customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
                response_deserializer=customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/customer_comex_visitor.CustomerComexVisitorController/Destroy',
                request_serializer=customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CustomerComexVisitorControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerComexVisitorControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=customer__comex__visitor__pb2.CustomerComexVisitorListRequest.FromString,
                    response_serializer=customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
                    response_serializer=customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=customer__comex__visitor__pb2.CustomerComexVisitorRetrieveRequest.FromString,
                    response_serializer=customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
                    response_serializer=customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customer_comex_visitor.CustomerComexVisitorController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerComexVisitorController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/customer_comex_visitor.CustomerComexVisitorController/List',
            customer__comex__visitor__pb2.CustomerComexVisitorListRequest.SerializeToString,
            customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer_comex_visitor.CustomerComexVisitorController/Create',
            customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
            customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer_comex_visitor.CustomerComexVisitorController/Retrieve',
            customer__comex__visitor__pb2.CustomerComexVisitorRetrieveRequest.SerializeToString,
            customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer_comex_visitor.CustomerComexVisitorController/Update',
            customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
            customer__comex__visitor__pb2.CustomerComexVisitor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customer_comex_visitor.CustomerComexVisitorController/Destroy',
            customer__comex__visitor__pb2.CustomerComexVisitor.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
