# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\x12\x08\x63ustomer\x1a\x1bgoogle/protobuf/empty.proto\"\x92\x02\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63reated_date\x18\x02 \x01(\t\x12\x14\n\x0cupdated_date\x18\x03 \x01(\t\x12\x1c\n\x14sejam_reference_code\x18\x04 \x01(\t\x12\x1c\n\x14normal_national_code\x18\x05 \x01(\t\x12\x11\n\tuser_name\x18\x06 \x01(\t\x12\x10\n\x08password\x18\x07 \x01(\t\x12\x11\n\tis_active\x18\x08 \x01(\x08\x12\x18\n\x10is_rayan_service\x18\t \x01(\x08\x12\x11\n\tis_sejami\x18\n \x01(\x08\x12\x12\n\nsejam_type\x18\x0b \x01(\t\x12\x19\n\x11rayan_customer_id\x18\x0c \x01(\t\"\x15\n\x13\x43ustomerListRequest\"%\n\x17\x43ustomerRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xb9\x02\n\x12\x43ustomerController\x12=\n\x04List\x12\x1d.customer.CustomerListRequest\x1a\x12.customer.Customer\"\x00\x30\x01\x12\x32\n\x06\x43reate\x12\x12.customer.Customer\x1a\x12.customer.Customer\"\x00\x12\x43\n\x08Retrieve\x12!.customer.CustomerRetrieveRequest\x1a\x12.customer.Customer\"\x00\x12\x32\n\x06Update\x12\x12.customer.Customer\x1a\x12.customer.Customer\"\x00\x12\x37\n\x07\x44\x65stroy\x12\x12.customer.Customer\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_CUSTOMER = DESCRIPTOR.message_types_by_name['Customer']
_CUSTOMERLISTREQUEST = DESCRIPTOR.message_types_by_name['CustomerListRequest']
_CUSTOMERRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['CustomerRetrieveRequest']
Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMER,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.Customer)
  })
_sym_db.RegisterMessage(Customer)

CustomerListRequest = _reflection.GeneratedProtocolMessageType('CustomerListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERLISTREQUEST,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerListRequest)
  })
_sym_db.RegisterMessage(CustomerListRequest)

CustomerRetrieveRequest = _reflection.GeneratedProtocolMessageType('CustomerRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERRETRIEVEREQUEST,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerRetrieveRequest)
  })
_sym_db.RegisterMessage(CustomerRetrieveRequest)

_CUSTOMERCONTROLLER = DESCRIPTOR.services_by_name['CustomerController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMER._serialized_start=58
  _CUSTOMER._serialized_end=332
  _CUSTOMERLISTREQUEST._serialized_start=334
  _CUSTOMERLISTREQUEST._serialized_end=355
  _CUSTOMERRETRIEVEREQUEST._serialized_start=357
  _CUSTOMERRETRIEVEREQUEST._serialized_end=394
  _CUSTOMERCONTROLLER._serialized_start=397
  _CUSTOMERCONTROLLER._serialized_end=710
# @@protoc_insertion_point(module_scope)
