# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: province.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprovince.proto\x12\x08province\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x0c\x42\x61seProvince\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x11rayan_province_id\x18\x03 \x01(\t\"\x19\n\x17\x42\x61seProvinceListRequest\")\n\x1b\x42\x61seProvinceRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xe1\x02\n\x16\x42\x61seProvinceController\x12\x45\n\x04List\x12!.province.BaseProvinceListRequest\x1a\x16.province.BaseProvince\"\x00\x30\x01\x12:\n\x06\x43reate\x12\x16.province.BaseProvince\x1a\x16.province.BaseProvince\"\x00\x12K\n\x08Retrieve\x12%.province.BaseProvinceRetrieveRequest\x1a\x16.province.BaseProvince\"\x00\x12:\n\x06Update\x12\x16.province.BaseProvince\x1a\x16.province.BaseProvince\"\x00\x12;\n\x07\x44\x65stroy\x12\x16.province.BaseProvince\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_BASEPROVINCE = DESCRIPTOR.message_types_by_name['BaseProvince']
_BASEPROVINCELISTREQUEST = DESCRIPTOR.message_types_by_name['BaseProvinceListRequest']
_BASEPROVINCERETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['BaseProvinceRetrieveRequest']
BaseProvince = _reflection.GeneratedProtocolMessageType('BaseProvince', (_message.Message,), {
  'DESCRIPTOR' : _BASEPROVINCE,
  '__module__' : 'province_pb2'
  # @@protoc_insertion_point(class_scope:province.BaseProvince)
  })
_sym_db.RegisterMessage(BaseProvince)

BaseProvinceListRequest = _reflection.GeneratedProtocolMessageType('BaseProvinceListRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASEPROVINCELISTREQUEST,
  '__module__' : 'province_pb2'
  # @@protoc_insertion_point(class_scope:province.BaseProvinceListRequest)
  })
_sym_db.RegisterMessage(BaseProvinceListRequest)

BaseProvinceRetrieveRequest = _reflection.GeneratedProtocolMessageType('BaseProvinceRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASEPROVINCERETRIEVEREQUEST,
  '__module__' : 'province_pb2'
  # @@protoc_insertion_point(class_scope:province.BaseProvinceRetrieveRequest)
  })
_sym_db.RegisterMessage(BaseProvinceRetrieveRequest)

_BASEPROVINCECONTROLLER = DESCRIPTOR.services_by_name['BaseProvinceController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASEPROVINCE._serialized_start=57
  _BASEPROVINCE._serialized_end=124
  _BASEPROVINCELISTREQUEST._serialized_start=126
  _BASEPROVINCELISTREQUEST._serialized_end=151
  _BASEPROVINCERETRIEVEREQUEST._serialized_start=153
  _BASEPROVINCERETRIEVEREQUEST._serialized_end=194
  _BASEPROVINCECONTROLLER._serialized_start=197
  _BASEPROVINCECONTROLLER._serialized_end=550
# @@protoc_insertion_point(module_scope)
