# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service.client.rayan.infrastructure.rayan_pb2 as rayan__pb2


class RecommendationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FundLicenseService = channel.unary_unary(
                '/Recommendations/FundLicenseService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundLicenseServiceResponse.FromString,
                )
        self.FundCustomerListService = channel.unary_unary(
                '/Recommendations/FundCustomerListService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundCustomerListServiceResponse.FromString,
                )
        self.FundCustomerInfoService = channel.unary_unary(
                '/Recommendations/FundCustomerInfoService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundCustomerInfoServiceResponse.FromString,
                )
        self.FunOrderService = channel.unary_unary(
                '/Recommendations/FunOrderService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FunOrderServiceResponse.FromString,
                )
        self.FundNavInfoService = channel.unary_unary(
                '/Recommendations/FundNavInfoService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundNavInfoServiceResponse.FromString,
                )
        self.FundStatisticInfoService = channel.unary_unary(
                '/Recommendations/FundStatisticInfoService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundStatisticInfoServiceResponse.FromString,
                )
        self.FundOrderReportsService = channel.unary_unary(
                '/Recommendations/FundOrderReportsService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundOrderReportsServiceResponse.FromString,
                )
        self.FundCustomerProfitsService = channel.unary_unary(
                '/Recommendations/FundCustomerProfitsService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundCustomerProfitsServiceResponse.FromString,
                )
        self.FundCustomerStatementService = channel.unary_unary(
                '/Recommendations/FundCustomerStatementService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundCustomerStatementServiceResponse.FromString,
                )
        self.FundBankAccountTypeService = channel.unary_unary(
                '/Recommendations/FundBankAccountTypeService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundBankAccountTypeServiceResponse.FromString,
                )
        self.FundIssueTypeService = channel.unary_unary(
                '/Recommendations/FundIssueTypeService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundIssueTypeServiceResponse.FromString,
                )
        self.FundInfoService = channel.unary_unary(
                '/Recommendations/FundInfoService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundInfoServiceResponse.FromString,
                )
        self.FundInvestmentManagersService = channel.unary_unary(
                '/Recommendations/FundInvestmentManagersService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundInvestmentManagersServiceResponse.FromString,
                )
        self.FundSaveIpoService = channel.unary_unary(
                '/Recommendations/FundSaveIpoService',
                request_serializer=rayan__pb2.FundSaveIpoRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundSaveIpoServiceResponse.FromString,
                )
        self.BrokerCustomerListService = channel.unary_unary(
                '/Recommendations/BrokerCustomerListService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.BrokerCustomerListServiceResponse.FromString,
                )
        self.BrokerCustomerService = channel.unary_unary(
                '/Recommendations/BrokerCustomerService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.BrokerCustomerServiceResponse.FromString,
                )
        self.FundSaveCancelOrderService = channel.unary_unary(
                '/Recommendations/FundSaveCancelOrderService',
                request_serializer=rayan__pb2.FundSaveCancelOrderRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundSaveCancelOrderServiceResponse.FromString,
                )
        self.FundChartService = channel.unary_unary(
                '/Recommendations/FundChartService',
                request_serializer=rayan__pb2.FundChartRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundChartServiceResponse.FromString,
                )
        self.RayanAccountService = channel.unary_unary(
                '/Recommendations/RayanAccountService',
                request_serializer=rayan__pb2.Request.SerializeToString,
                response_deserializer=rayan__pb2.RayanAccountResponse.FromString,
                )
        self.FundChartDbService = channel.unary_unary(
                '/Recommendations/FundChartDbService',
                request_serializer=rayan__pb2.Request.SerializeToString,
                response_deserializer=rayan__pb2.FundChartDbResponse.FromString,
                )
        self.FundCancelOrderService = channel.unary_unary(
                '/Recommendations/FundCancelOrderService',
                request_serializer=rayan__pb2.FundCancelOrderRequest.SerializeToString,
                response_deserializer=rayan__pb2.FundCancelOrderServiceResponse.FromString,
                )
        self.RayanAccountImageService = channel.unary_unary(
                '/Recommendations/RayanAccountImageService',
                request_serializer=rayan__pb2.MainRequest.SerializeToString,
                response_deserializer=rayan__pb2.RayanAccountImageResponse.FromString,
                )


class RecommendationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FundLicenseService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundCustomerListService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundCustomerInfoService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FunOrderService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundNavInfoService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundStatisticInfoService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundOrderReportsService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundCustomerProfitsService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundCustomerStatementService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundBankAccountTypeService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundIssueTypeService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundInfoService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundInvestmentManagersService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundSaveIpoService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrokerCustomerListService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrokerCustomerService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundSaveCancelOrderService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundChartService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RayanAccountService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundChartDbService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundCancelOrderService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RayanAccountImageService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FundLicenseService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundLicenseService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundLicenseServiceResponse.SerializeToString,
            ),
            'FundCustomerListService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundCustomerListService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundCustomerListServiceResponse.SerializeToString,
            ),
            'FundCustomerInfoService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundCustomerInfoService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundCustomerInfoServiceResponse.SerializeToString,
            ),
            'FunOrderService': grpc.unary_unary_rpc_method_handler(
                    servicer.FunOrderService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FunOrderServiceResponse.SerializeToString,
            ),
            'FundNavInfoService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundNavInfoService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundNavInfoServiceResponse.SerializeToString,
            ),
            'FundStatisticInfoService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundStatisticInfoService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundStatisticInfoServiceResponse.SerializeToString,
            ),
            'FundOrderReportsService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundOrderReportsService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundOrderReportsServiceResponse.SerializeToString,
            ),
            'FundCustomerProfitsService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundCustomerProfitsService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundCustomerProfitsServiceResponse.SerializeToString,
            ),
            'FundCustomerStatementService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundCustomerStatementService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundCustomerStatementServiceResponse.SerializeToString,
            ),
            'FundBankAccountTypeService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundBankAccountTypeService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundBankAccountTypeServiceResponse.SerializeToString,
            ),
            'FundIssueTypeService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundIssueTypeService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundIssueTypeServiceResponse.SerializeToString,
            ),
            'FundInfoService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundInfoService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundInfoServiceResponse.SerializeToString,
            ),
            'FundInvestmentManagersService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundInvestmentManagersService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.FundInvestmentManagersServiceResponse.SerializeToString,
            ),
            'FundSaveIpoService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundSaveIpoService,
                    request_deserializer=rayan__pb2.FundSaveIpoRequest.FromString,
                    response_serializer=rayan__pb2.FundSaveIpoServiceResponse.SerializeToString,
            ),
            'BrokerCustomerListService': grpc.unary_unary_rpc_method_handler(
                    servicer.BrokerCustomerListService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.BrokerCustomerListServiceResponse.SerializeToString,
            ),
            'BrokerCustomerService': grpc.unary_unary_rpc_method_handler(
                    servicer.BrokerCustomerService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.BrokerCustomerServiceResponse.SerializeToString,
            ),
            'FundSaveCancelOrderService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundSaveCancelOrderService,
                    request_deserializer=rayan__pb2.FundSaveCancelOrderRequest.FromString,
                    response_serializer=rayan__pb2.FundSaveCancelOrderServiceResponse.SerializeToString,
            ),
            'FundChartService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundChartService,
                    request_deserializer=rayan__pb2.FundChartRequest.FromString,
                    response_serializer=rayan__pb2.FundChartServiceResponse.SerializeToString,
            ),
            'RayanAccountService': grpc.unary_unary_rpc_method_handler(
                    servicer.RayanAccountService,
                    request_deserializer=rayan__pb2.Request.FromString,
                    response_serializer=rayan__pb2.RayanAccountResponse.SerializeToString,
            ),
            'FundChartDbService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundChartDbService,
                    request_deserializer=rayan__pb2.Request.FromString,
                    response_serializer=rayan__pb2.FundChartDbResponse.SerializeToString,
            ),
            'FundCancelOrderService': grpc.unary_unary_rpc_method_handler(
                    servicer.FundCancelOrderService,
                    request_deserializer=rayan__pb2.FundCancelOrderRequest.FromString,
                    response_serializer=rayan__pb2.FundCancelOrderServiceResponse.SerializeToString,
            ),
            'RayanAccountImageService': grpc.unary_unary_rpc_method_handler(
                    servicer.RayanAccountImageService,
                    request_deserializer=rayan__pb2.MainRequest.FromString,
                    response_serializer=rayan__pb2.RayanAccountImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Recommendations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recommendations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FundLicenseService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundLicenseService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundLicenseServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundCustomerListService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundCustomerListService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundCustomerListServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundCustomerInfoService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundCustomerInfoService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundCustomerInfoServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FunOrderService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FunOrderService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FunOrderServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundNavInfoService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundNavInfoService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundNavInfoServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundStatisticInfoService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundStatisticInfoService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundStatisticInfoServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundOrderReportsService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundOrderReportsService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundOrderReportsServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundCustomerProfitsService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundCustomerProfitsService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundCustomerProfitsServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundCustomerStatementService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundCustomerStatementService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundCustomerStatementServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundBankAccountTypeService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundBankAccountTypeService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundBankAccountTypeServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundIssueTypeService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundIssueTypeService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundIssueTypeServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundInfoService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundInfoService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundInfoServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundInvestmentManagersService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundInvestmentManagersService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.FundInvestmentManagersServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundSaveIpoService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundSaveIpoService',
            rayan__pb2.FundSaveIpoRequest.SerializeToString,
            rayan__pb2.FundSaveIpoServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BrokerCustomerListService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/BrokerCustomerListService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.BrokerCustomerListServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BrokerCustomerService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/BrokerCustomerService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.BrokerCustomerServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundSaveCancelOrderService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundSaveCancelOrderService',
            rayan__pb2.FundSaveCancelOrderRequest.SerializeToString,
            rayan__pb2.FundSaveCancelOrderServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundChartService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundChartService',
            rayan__pb2.FundChartRequest.SerializeToString,
            rayan__pb2.FundChartServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RayanAccountService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/RayanAccountService',
            rayan__pb2.Request.SerializeToString,
            rayan__pb2.RayanAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundChartDbService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundChartDbService',
            rayan__pb2.Request.SerializeToString,
            rayan__pb2.FundChartDbResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundCancelOrderService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/FundCancelOrderService',
            rayan__pb2.FundCancelOrderRequest.SerializeToString,
            rayan__pb2.FundCancelOrderServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RayanAccountImageService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendations/RayanAccountImageService',
            rayan__pb2.MainRequest.SerializeToString,
            rayan__pb2.RayanAccountImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
